env:
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  max-len:
    - error
    - code: 140
  no-console:
    - error
  prefer-arrow-callback:
    - error
